service: import-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '3'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: dev
  httpApi:
    cors: true
  iam:
    role:
      statements:
        # Probably is bad practice, but for HM project is ok
        - Effect: Allow
          Action:
            - s3:*
          Resource: "*"
functions:
  importProductsFile:
    handler: handlers/importProductsFile.handler
    events:
      - httpApi:
          method: get
          path: /import
  importFileParser:
    handler: handlers/importFileParser.handler
    events:
      - s3:
          bucket: import-service-yn
          event: s3:ObjectCreated:*
          rules: 
              - prefix: uploaded/
          existing: true
