service: import-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '3'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: dev
  httpApi:
    cors: true
  environment:
   SQS_QUEUE_URL: { Ref: NewSQSQueue } # can be accessible as env.SQS_QUEUE_URL
  iam:
    role:
      statements:
        # Probably is bad practice, but for HM project is ok
        - Effect: Allow
          Action:
            - s3:*
          Resource: "*"
        - Effect: Allow
          Action:
            - sqs:*
          Resource:
            Fn::GetAtt: [ NewSQSQueue, Arn ]
functions:
  importProductsFile:
    handler: handlers/importProductsFile.handler
    events:
      - httpApi:
          method: get
          path: /import
  importFileParser:
    handler: handlers/importFileParser.handler
    events:
      - s3:
          bucket: import-service-yn
          event: s3:ObjectCreated:*
          rules: 
              - prefix: uploaded/
          existing: true
  catalogBatchProcess:
    handler: handlers/catalogBatchProcess.handler
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt:
              - NewSQSQueue
              - Arn
resources:
 Resources:
   NewSQSQueue:
     Type: "AWS::SQS::Queue"
     Properties:
       QueueName: catalogItemsQueue
